// <auto-generated />
namespace Forum.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class changes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changes));
        
        string IMigrationMetadata.Id
        {
            get { return "201405280731077_changes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
