//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Forum
{
    using System;
    using System.Collections.Generic;
    
    public partial class Messages
    {
        public Messages()
        {
            this.Questions = new HashSet<Questions>();
        }
    
        public int Id { get; set; }
        public string Question_Id { get; set; }
        public string Message_text { get; set; }
    
        public virtual ICollection<Questions> Questions { get; set; }
    }
}
