//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Forum
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Model1Container : DbContext
    {
        public Model1Container()
            : base("name=Model1Container")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Questions> QuestionsSet { get; set; }
        public DbSet<QuestionGroups> QuestionGroupsSet { get; set; }
        public DbSet<UserProfiles> UserProfilesSet { get; set; }
        public DbSet<UserRoles> UserRolesSet { get; set; }
        public DbSet<Messages> MessagesSet { get; set; }
    }
}
