//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Forum
{
    using System;
    using System.Collections.Generic;
    
    public partial class Questions
    {
        public Questions()
        {
            this.QuestionGroups = new HashSet<QuestionGroups>();
        }
    
        public int Id { get; set; }
        public string QuestionGroup_Id { get; set; }
        public string User_Id { get; set; }
        public string Question_name { get; set; }
        public string Date { get; set; }
        public string Handled { get; set; }
    
        public virtual ICollection<QuestionGroups> QuestionGroups { get; set; }
        public virtual UserProfiles UserProfiles { get; set; }
        public virtual Messages Messages { get; set; }
    }
}
