//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Forum
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProfiles
    {
        public UserProfiles()
        {
            this.UserRoles = new HashSet<UserRoles>();
            this.Questions = new HashSet<Questions>();
        }
    
        public int Id { get; set; }
        public string Role_Id { get; set; }
        public string Username { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string Password { get; set; }
    
        public virtual ICollection<UserRoles> UserRoles { get; set; }
        public virtual ICollection<Questions> Questions { get; set; }
    }
}
